/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package provemax_grupo_5.Vistas;

import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author July
 */
public class Provemax extends javax.swing.JFrame {
    

    /**
     * Creates new form Provemax
     */
    public Provemax() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        ImageIcon icono = new ImageIcon(getClass().getResource("/provemax_grupo_5/Recursos/Foto de Supermercado.jpg"));
        Image miImagen = icono.getImage();
        escritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCompra = new javax.swing.JMenu();
        jMICompraProductos = new javax.swing.JMenuItem();
        jMIDetalle = new javax.swing.JMenuItem();
        jMProductos = new javax.swing.JMenu();
        jMIListProductos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMProveedores = new javax.swing.JMenu();
        jMIRegistroProv = new javax.swing.JMenuItem();
        pXNombre = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMCompra.setText("Compra");

        jMICompraProductos.setText("Compra de Productos");
        jMICompraProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICompraProductosActionPerformed(evt);
            }
        });
        jMCompra.add(jMICompraProductos);

        jMIDetalle.setText("Detalle de Compra");
        jMCompra.add(jMIDetalle);

        jMenuBar1.add(jMCompra);

        jMProductos.setText("Productos");

        jMIListProductos.setText("Lista de Productos");
        jMIListProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIListProductosActionPerformed(evt);
            }
        });
        jMProductos.add(jMIListProductos);

        jMenuItem2.setText("Productos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMProductos.add(jMenuItem2);

        jMenuBar1.add(jMProductos);

        jMProveedores.setText("Proveedores");

        jMIRegistroProv.setText("Registro de Proveedores");
        jMIRegistroProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegistroProvActionPerformed(evt);
            }
        });
        jMProveedores.add(jMIRegistroProv);

        jMenuBar1.add(jMProveedores);

        pXNombre.setText("Consultas");

        jMenuItem1.setText("Productos por nombre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        pXNombre.add(jMenuItem1);

        jMenuBar1.add(pXNombre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        escritorio.removeAll();
        escritorio.repaint();
        ProductosPorNombre ppn = new ProductosPorNombre();
        ppn.setVisible(true);
        escritorio.add(ppn);
        escritorio.moveToFront(ppn);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMIListProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIListProductosActionPerformed
        // TODO add your handling code here:

        escritorio.removeAll();
        escritorio.repaint();
        ListaDeProductos ldp = new ListaDeProductos();

    }//GEN-LAST:event_jMIListProductosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        Productos pros=new Productos();
        pros.setVisible(true);
        escritorio.add(pros);
        escritorio.moveToFront(pros);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMIRegistroProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegistroProvActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        RegistroDeProveedores rdp =new RegistroDeProveedores();
        rdp.setVisible(true);
        escritorio.add(rdp);
        escritorio.moveToFront(rdp);
    }//GEN-LAST:event_jMIRegistroProvActionPerformed

    private void jMICompraProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICompraProductosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Compras comp = new Compras();
        comp.setVisible(true);
        escritorio.add(comp);
        escritorio.moveToFront(comp);
    }//GEN-LAST:event_jMICompraProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provemax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provemax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provemax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provemax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provemax().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMCompra;
    private javax.swing.JMenuItem jMICompraProductos;
    private javax.swing.JMenuItem jMIDetalle;
    private javax.swing.JMenuItem jMIListProductos;
    private javax.swing.JMenuItem jMIRegistroProv;
    private javax.swing.JMenu jMProductos;
    private javax.swing.JMenu jMProveedores;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu pXNombre;
    // End of variables declaration//GEN-END:variables
}
